WGMVC/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WGMVC;

namespace WGMVC.Controllers
{ 
    public class CategoryController : Controller
    {
        private WGEntities db = new WGEntities();

        //
        // GET: /Category/

        public ViewResult Index()
        {
            return View(db.WGCategories.ToList());
        }

        //
        // GET: /Category/Details/5

        public ViewResult Details(int id)
        {
            WGCategory wgcategory = db.WGCategories.Single(w => w.Id == id);
            return View(wgcategory);
        }

        //
        // GET: /Category/Create
         [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Category/Create

        [HttpPost]
        [Authorize(Roles = "admin")]
        public ActionResult Create(WGCategory wgcategory)
        {
            if (ModelState.IsValid)
            {
                db.WGCategories.AddObject(wgcategory);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            return View(wgcategory);
        }
        
        //
        // GET: /Category/Edit/5
  [Authorize(Roles = "admin")]
        public ActionResult Edit(int id)
        {
            WGCategory wgcategory = db.WGCategories.Single(w => w.Id == id);
            return View(wgcategory);
        }

        //
        // POST: /Category/Edit/5

        [HttpPost]
        [Authorize(Roles = "admin")]
        public ActionResult Edit(WGCategory wgcategory)
        {
            if (ModelState.IsValid)
            {
                db.WGCategories.Attach(wgcategory);
                db.ObjectStateManager.ChangeObjectState(wgcategory, EntityState.Modified);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(wgcategory);
        }

        //
        // GET: /Category/Delete/5
  [Authorize(Roles = "admin")]
        public ActionResult Delete(int id)
        {
            WGCategory wgcategory = db.WGCategories.Single(w => w.Id == id);
            return View(wgcategory);
        }

        //
        // POST: /Category/Delete/5

        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "admin")]
        public ActionResult DeleteConfirmed(int id)
        {            
            WGCategory wgcategory = db.WGCategories.Single(w => w.Id == id);
            db.WGCategories.DeleteObject(wgcategory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

WGMVC/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WGMVC;
using PagedList;
using PagedList.Mvc;

namespace WGMVC.Controllers
{ 
    public class ProductController : Controller
    {
        private WGEntities db = new WGEntities();

        //
        // GET: /Product/

        //for filtering, the parameter will match the name of the drop down,which came form the name of the slelcted 
        //list in the viewbag
        //3 parameters  for the SelectedList- data,valuefield, text field

        public ViewResult Index(int? CategoryId, string search,string newSearch, int page =1 )
        {
            int pageSize = 6;

            if (!string.IsNullOrEmpty(newSearch))
            {
                page = 1;
            }


            //add a selectList to the View bag for the category ddl filter
            ViewBag.CategoryId = new SelectList(db.WGCategories.OrderBy(x => x.Name),
                "Id", "Name");
            //convert th object set to a list to make it easier to filter
            var wgproducts = db.WgProducts.Include("WGCategory").Include("WGStatu").Include("WGVendor").OrderBy(x=> x.name).ToList();
            if (!User.IsInRole("admin"))
            {
                wgproducts = (from prod in wgproducts
                              where prod.StatusID < 4
                              select prod).ToList();
            }


            //if categoryID is not null, we will filter by category Id
            if (CategoryId !=null)
            {
                wgproducts = (from prod in wgproducts
                              where prod.CategoryID == CategoryId
                              select prod).ToList();
            }
           
            //if search is not null or empthp apply the search
            if (!String.IsNullOrEmpty(search))
            {
                search = search.ToLower();
                wgproducts = (from prod in wgproducts
                              where prod.name.ToLower().Contains(search) ||
                              (prod.Description != null &&
                              prod.Description.ToLower().Contains(search))
                              select prod).ToList();

            }

            //save the filter value to the viewbag for the pager

            ViewBag.CurrentSearch = search;
            ViewBag.CurrentCategory = CategoryId;

            return View(wgproducts.ToPagedList(page, pageSize));
        }

        //
        // GET: /Product/Details/5

        public ViewResult Details(int id)
        {


            WgProduct wgproduct = db.WgProducts.Single(w => w.ID == id);
            return View(wgproduct);
        }

        //
        // GET: /Product/Create
        //admin only action
        [Authorize(Roles="admin")]
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.WGCategories, "Id", "Name");
            ViewBag.StatusID = new SelectList(db.WGStatus, "ID", "Name");
            ViewBag.VendorID = new SelectList(db.WGVendors, "ID", "Name");
            return View();
        } 

        //
        // POST: /Product/Create

        [HttpPost]
        [Authorize(Roles = "admin")]
        //for the file upload 

        public ActionResult Create(WgProduct wgproduct, HttpPostedFileBase productImage )
        {
            if (ModelState.IsValid)
            {
                //make sure user uploaded file
                if (productImage != null)
                {
                    
              
                //get the file name 
                string filename = productImage.FileName;
                //get the ext
                    string ext = filename.Substring(filename.LastIndexOf("."));
                //rename file using a GUID  and add the ext back
                    string newFile = Guid.NewGuid().ToString() + ext;
                //save that file to the content/img directory
                    productImage.SaveAs(
                        Server.MapPath("~/Content/Img/"+ newFile));
                //save the new file  name in the product object
                    wgproduct.ImageUrl = newFile;
  }


                else
                {
                    //no file  uploaded, us the noimage.jpg
                    wgproduct.ImageUrl = "No_image_available.jpg";
                }
                db.WgProducts.AddObject(wgproduct);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            ViewBag.CategoryID = new SelectList(db.WGCategories, "Id", "Name", wgproduct.CategoryID);
            ViewBag.StatusID = new SelectList(db.WGStatus, "ID", "Name", wgproduct.StatusID);
            ViewBag.VendorID = new SelectList(db.WGVendors, "ID", "Name", wgproduct.VendorID);
            return View(wgproduct);
        }
        
        //
        // GET: /Product/Edit/5
  [Authorize(Roles = "admin")]
        public ActionResult Edit(int id)
        {
            WgProduct wgproduct = db.WgProducts.Single(w => w.ID == id);
            ViewBag.CategoryID = new SelectList(db.WGCategories, "Id", "Name", wgproduct.CategoryID);
            ViewBag.StatusID = new SelectList(db.WGStatus, "ID", "Name", wgproduct.StatusID);
            ViewBag.VendorID = new SelectList(db.WGVendors, "ID", "Name", wgproduct.VendorID);
            return View(wgproduct);
        }

        //
        // POST: /Product/Edit/5

        [HttpPost]
        [Authorize(Roles = "admin")]
        public ActionResult Edit(WgProduct wgproduct, HttpPostedFileBase productImage)
        {
            if (ModelState.IsValid)
            {
                if (productImage != null)
                {


                    //get the file name 
                    string filename = productImage.FileName;
                    //get the ext
                    string ext = filename.Substring(filename.LastIndexOf("."));
                    //rename file using a GUID  and add the ext back
                    string newFile = Guid.NewGuid().ToString() + ext;
                    //save that file to the content/img directory
                    productImage.SaveAs(
                        Server.MapPath("~/Content/Img/" + newFile));
                    //save the new file  name in the product object
                    wgproduct.ImageUrl = newFile;
                }
                
                
                
                db.WgProducts.Attach(wgproduct);
                db.ObjectStateManager.ChangeObjectState(wgproduct, EntityState.Modified);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryID = new SelectList(db.WGCategories, "Id", "Name", wgproduct.CategoryID);
            ViewBag.StatusID = new SelectList(db.WGStatus, "ID", "Name", wgproduct.StatusID);
            ViewBag.VendorID = new SelectList(db.WGVendors, "ID", "Name", wgproduct.VendorID);
            return View(wgproduct);
        }

        //
        // GET: /Product/Delete/5
  [Authorize(Roles = "admin")]
        public ActionResult Delete(int id)
        {
            WgProduct wgproduct = db.WgProducts.Single(w => w.ID == id);
            return View(wgproduct);
        }

        //
        // POST: /Product/Delete/5

        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "admin")]
        public ActionResult DeleteConfirmed(int id)
        {            
            WgProduct wgproduct = db.WgProducts.Single(w => w.ID == id);
            //db.WgProducts.DeleteObject(wgproduct);
            wgproduct.StatusID = 4;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

WGMVC/Controllers/StatusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WGMVC;

namespace WGMVC.Controllers
{
    [Authorize(Roles = "admin")]
    public class StatusController : Controller
    {
        private WGEntities db = new WGEntities();

        //
        // GET: /Status/

        public ViewResult Index()
        {
            return View(db.WGStatus.ToList());
        }

        //
        // GET: /Status/Details/5

        public ViewResult Details(int id)
        {
            WGStatu wgstatu = db.WGStatus.Single(w => w.ID == id);
            return View(wgstatu);
        }

        //
        // GET: /Status/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Status/Create

        [HttpPost]
        public ActionResult Create(WGStatu wgstatu)
        {
            if (ModelState.IsValid)
            {
                db.WGStatus.AddObject(wgstatu);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            return View(wgstatu);
        }
        
        //
        // GET: /Status/Edit/5
 
        public ActionResult Edit(int id)
        {
            WGStatu wgstatu = db.WGStatus.Single(w => w.ID == id);
            return View(wgstatu);
        }

        //
        // POST: /Status/Edit/5

        [HttpPost]
        public ActionResult Edit(WGStatu wgstatu)
        {
            if (ModelState.IsValid)
            {
                db.WGStatus.Attach(wgstatu);
                db.ObjectStateManager.ChangeObjectState(wgstatu, EntityState.Modified);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(wgstatu);
        }

        //
        // GET: /Status/Delete/5
 
        public ActionResult Delete(int id)
        {
            WGStatu wgstatu = db.WGStatus.Single(w => w.ID == id);
            return View(wgstatu);
        }

        //
        // POST: /Status/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            WGStatu wgstatu = db.WGStatus.Single(w => w.ID == id);
            db.WGStatus.DeleteObject(wgstatu);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

WGMVC/Controllers/VendorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WGMVC;
using PagedList;
using PagedList.Mvc;


namespace WGMVC.Controllers
{
     [Authorize(Roles = "admin")]
    public class VendorController : Controller
    {
        private WGEntities db = new WGEntities();

        //
        // GET: /Vendor/
         //for the pager, we need a parameter for the pageNumber
        public ViewResult Index(int page=1)
        {
            int pageSize = 2;

            return View(db.WGVendors.OrderBy(x =>x.Name).ToList().ToPagedList(page, pageSize));
        }

        //
        // GET: /Vendor/Details/5

        public ViewResult Details(int id)
        {
            WGVendor wgvendor = db.WGVendors.Single(w => w.ID == id);
            return View(wgvendor);
        }

        //
        // GET: /Vendor/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Vendor/Create

        [HttpPost]
        public ActionResult Create(WGVendor wgvendor)
        {
            if (ModelState.IsValid)
            {
                db.WGVendors.AddObject(wgvendor);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            return View(wgvendor);
        }
        
        //
        // GET: /Vendor/Edit/5
 
        public ActionResult Edit(int id)
        {
            WGVendor wgvendor = db.WGVendors.Single(w => w.ID == id);
            return View(wgvendor);
        }

        //
        // POST: /Vendor/Edit/5

        [HttpPost]
        public ActionResult Edit(WGVendor wgvendor)
        {
            if (ModelState.IsValid)
            {
                db.WGVendors.Attach(wgvendor);
                db.ObjectStateManager.ChangeObjectState(wgvendor, EntityState.Modified);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(wgvendor);
        }

        //
        // GET: /Vendor/Delete/5
 
        public ActionResult Delete(int id)
        {
            WGVendor wgvendor = db.WGVendors.Single(w => w.ID == id);
            return View(wgvendor);
        }

        //
        // POST: /Vendor/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            WGVendor wgvendor = db.WGVendors.Single(w => w.ID == id);
            db.WGVendors.DeleteObject(wgvendor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

WGMVC/Views/Shared/_Layout.cshtml
<!doctype html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>@ViewBag.Title</title>
    <meta name="description" content="" />
    <meta name="keyword" content="" />


    <link rel="stylesheet" href="@Url.Content("~/Content/css/reset.css")" type="text/css" />
    <link rel="stylesheet" href="@Url.Content("~/Content/css/styles.css")" type="text/css" />    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="@Url.Content("~/Content/PagedList.css")" type="text/css" />

    <!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

    <script type="text/javascript" src="@Url.Content("~/scripts/js/jquery.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/scripts/js/slider.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/scripts/js/superfish.js")"></script>

    <script type="text/javascript" src="@Url.Content("~/scripts/js/custom.js")"></script>

    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0" />

    <script>
        //code for the selected link
        $(function () {
            //get each of the nav links
            $(".mainNav a").each(function () {
                var a = $(this);
                if (a.attr('href') == window.location.pathname) {
                    a.parent('li').addClass("selected");
                    //for the sidebar links 
                    a.addClass("selected");
                }

            });
        });

    </script>

    <!--
city, a free CSS web template by ZyPOP (zypopwebtemplates.com/)

Download: http://zypopwebtemplates.com/

License: Creative Commons Attribution
//-->
</head>
<body>
    <div id="container">

        <header>
            <div class="width">

                <h1><a href="/">Widgets<strong>&amp</strong>Gadgets</a></h1>

                <nav>

                    <ul class="sf-menu dropdown mainNav"  >


                        <li ><a href="@Url.Action("Index","Home")"><i class="fa fa-home"></i>Home</a></li>

                        <li>

                            <a href="@Url.Action("About","Home")"><i class="fa fa-male"></i>About</a>

                        </li>

           

                        <li>

                            <a href="@Url.Action("Index","Product")"><i class="fa fa-star"></i>Products</a>
                            @{
                                //go get category
                                var categories = new WGMVC.WGEntities().WGCategories.OrderBy(x => x.Name);
                                }
                            
                            <ul>
                                @foreach (var item in categories)
                                {
                                     <li>
                                         <a href="@Url.Action("Index", "Product", new {CategoryId = item.Id })">@item.Name</a>
                                     </li>
                                }
                               
                            </ul>
                           

                        </li>

                        <li><a href="@Url.Action("Contact", "Home")"><i class="fa fa-phone"></i>Contact</a></li>
                 <li >
                     @if (User.Identity.IsAuthenticated)
                     {
                         //user is logged in  
                         <a href="@Url.Action("LogOff","Account")"><i class="fa fa-lock"></i>Log Out</a>
                     }
                     else
                     { 
                            <a href="@Url.Action("LogOn","Account")"><i class="fa fa-lock"></i>Log On</a>
             
                     }
                     
                 </li>  
                        @*  *@
 </ul>
                    <div class="clear"></div>
                </nav>
            </div>

            <div class="clear"></div>


        </header>


        <div id="intro">

            <div class="width">
                @* sections ar optional content placeholders that the views can use to add content *@
                @RenderSection("intro",false)

            </div>


        </div>

        <div id="body" class="width">



            <section id="content" class="two-column with-right-sidebar">

                <article>
            @RenderBody()

                    


                </article>

     
            </section>

            <aside class="sidebar big-sidebar right-sidebar">


                <ul>
                 
                      <li>
   @if (User.Identity.IsAuthenticated)
                      {
                          <p> Welcom, @User.Identity.Name</p>
                      }
                          @if (User.IsInRole("admin"))
                          {
                                 <h4>Admin Menu</h4>
                        <ul class="blocklist mainNav">
                            <li><a  href="@Url.Action("Index","Category")">Manage Categories</a></li>
                          <li><a  href="@Url.Action("Index","Vendor")">Manage Vendors</a></li>
                            <li><a  href="@Url.Action("Index","Status")">Manage Products Statuses</a></li>
  </ul>
                          }
                     
                      
                    </li>





                  
                </ul>

            </aside>
            <div class="clear"></div>
        </div>
        <footer>
            <div class="footer-content width">
               

    

                        <div class="social-icons">

                            <a href="#"><i class="fa fa-facebook fa-2x"></i></a>

                            <a href="#"><i class="fa fa-twitter fa-2x"></i></a>

                            <a href="#"><i class="fa fa-youtube fa-2x"></i></a>

                            <a href="#"><i class="fa fa-instagram fa-2x"></i></a>

                        </div>

                 

                <div class="clear"></div>
            </div>
            <div class="footer-bottom">
                <p>&copy; Nerdevelment. Thanks to: <a href="http://zypopwebtemplates.com/">Free HTML5 Templates</a> by ZyPOP</p>
            </div>
        </footer>
    </div>
</body>
</html>

WGMVC/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}